### Send POST request with json body
POST http://localhost:8080/addvotes
Content-Type: application/json

{
  "code": "WP001",
  "technology": "Java",
  "votes": 1
}

### Send POST request with json body to create task
POST http://localhost:8080/votetask
Content-Type: application/json

{
  "code": "WC123",
  "technology": "Java",
  "votes": 1
}
